server:
  port: 8080

spring:
  datasource:
    name: tucu
    url: jdbc:mysql://127.0.0.1:3306/tucu?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
